### ISSUE TITLE
readme中提到的pretrained retriever models的路径是哪一个呢？

### ISSUE THREAD

**Issue by Salierioo** [18907305772/MAKER#1]
我在readme中给出的test脚本中发现，输入的参数中，retriever_model_name=RMN

在test.py的第270行，retrieve tokenizer的是frompretrain（opt.retriever_model_name）,

但紧接着第271行，retrieve model是frompretrain（opt.test_model_path.replace("generator", "retriever")），而opt.test_model_path=DOWNLOAD_PATH/MAKER-mwoz-condensed-kb-t5-base/generator_best_dev，这个路径是跟想要测试的数据集相关的，显然和前面tokenizer的路径不是同一个

我看两个文件夹里的config文件，两个模型都是BertForCL，这两个路径下的模型文件是同一个吗？

**Comment by 18907305772** [comment]
opt.retriever_model_name: 是预训练检索器的路径；
opt.test_model_path.replace("generator", "retriever"): 是整个系统训练完后检索器的路径；
这两个路径代表的模型是不一样的模型，但如果系统训练时，检索器参数没有更新，那么其权重不会改变。

**Comment by Salierioo** [comment]
> opt.retriever_model_name: 是预训练检索器的路径； opt.test_model_path.replace("generator", "retriever"): 是整个系统训练完后检索器的路径； 这两个路径代表的模型是不一样的模型，但如果系统训练时，检索器参数没有更新，那么其权重不会改变。


感谢回答，我明白了！

另外我还有个小问题就是，文中提到的condensed和full的KB大小设置是怎么体现的呢？

我看了readme中给出的condensed_mwoz的test脚本，对比了full_mwoz的test脚本，发现其中不同就是对于ranker的一些参数设置，我再看了一下ranker模型相关的代码，也没有找到针对这两个KB差异而产生的不同。

**Comment by 18907305772** [comment]
有一个参数：use_gt_dbs 
当这个参数设置为 True 时，就会使用 condensed KB，否则使用 full KB

**Comment by Salierioo** [comment]
感谢解答！
